import { IUser, ISession, IGoal, IAchievement, IReport } from "../types";

export interface IMockPitchTrendPoint {
  date: string;
  sessionTitle: string;
  accuracy: number;
  centsError: number;
  stability: number;
  target: number;
  score: number;
}

export interface IMockTempoTrendPoint {
  date: string;
  sessionTitle: string;
  measuredBpm: number;
  targetBpm: number;
  deviation: number;
  consistency: number;
}

export interface IMockVocalRange {
  lowestNote: string;
  lowestFreq: number;
  highestNote: string;
  highestFreq: number;
  tessituraStart: string;
  tessituraEnd: string;
  passaggioNote: string;
  totalSemitones: number;
  octaveSpan: string;
  registers: Array<{
    name: string;
    startNote: string;
    endNote: string;
    startFreq: number;
    endFreq: number;
    color: string;
    description: string;
  }>;
}

export interface IMockAiFeedback {
  healthScore: number;
  fatigueRisk: "Low" | "Moderate" | "High";
  vocalStrainStatus: string;
  summary: string;
  acousticProfile: {
    singersFormantHz: number;
    formantClarity: string;
    vibratoRateHz: number;
    vibratoDepthCents: number;
    breathEfficiency: number;
  };
  strengths: string[];
  areasForImprovement: string[];
  recommendedDrills: Array<{
    id: string;
    title: string;
    focus: string;
    duration: string;
    difficulty: "Beginner" | "Intermediate" | "Advanced" | "Master";
    targetArea: string;
    instructions: string;
  }>;
}

export const mockUser: IUser = {
  _id: "user-elena-vance-pro",
  name: "Elena Vance",
  email: "elena.vance@vocalytics.ai",
  avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80",
  voiceType: "Soprano",
  vocalType: "Soprano",
  skillLevel: "Advanced",
  experienceLevel: "Advanced",
  bio: "Classical crossover & cinematic pop vocalist. Focused on high-register tessitura stabilization, formant resonance amplification, and microtonal intonation control.",
  vocalRangeLowest: "C3",
  vocalRangeHighest: "A5",
  preferredGenres: ["Cinematic Pop", "Classical Crossover", "Chamber Vocal", "Contemporary R&B"],
  totalPracticeHours: 24.5,
  totalPracticeMinutes: 1470,
  totalSessionsCount: 84,
  averageScore: 92.4,
  currentStreak: 14,
  streakDays: 14,
  longestStreak: 28,
  lastPracticeDate: new Date().toISOString(),
  preferences: {
    darkTheme: true,
    autoAnalyze: true,
    notifications: true,
    audioInputDevice: "Shure SM7B - Focusrite Scarlett 2i2 USB",
  },
};

export const mockPitchTrend: IMockPitchTrendPoint[] = [
  { date: "Sep 12", sessionTitle: "Vocal Warmup Arpeggios", accuracy: 87.2, centsError: 15.4, stability: 85.0, target: 90, score: 86 },
  { date: "Sep 14", sessionTitle: "Rolling in the Deep (Take 1)", accuracy: 88.5, centsError: 13.8, stability: 87.2, target: 90, score: 88 },
  { date: "Sep 16", sessionTitle: "Hallelujah (Vocalise in D)", accuracy: 91.0, centsError: 11.2, stability: 89.5, target: 90, score: 90 },
  { date: "Sep 18", sessionTitle: "Passaggio Siren Drills", accuracy: 89.8, centsError: 12.0, stability: 88.0, target: 90, score: 89 },
  { date: "Sep 20", sessionTitle: "O Mio Babbino Caro (Tessitura)", accuracy: 93.4, centsError: 8.6, stability: 92.1, target: 90, score: 93 },
  { date: "Sep 22", sessionTitle: "Chandelier - Belt & Mix", accuracy: 92.0, centsError: 9.8, stability: 91.0, target: 90, score: 91 },
  { date: "Sep 24", sessionTitle: "Vibrato Centering Exercise", accuracy: 94.6, centsError: 7.2, stability: 93.8, target: 90, score: 94 },
  { date: "Sep 26", sessionTitle: "Fly Me to the Moon (Jazz Mix)", accuracy: 95.8, centsError: 6.1, stability: 94.5, target: 90, score: 96 },
  { date: "Sep 28", sessionTitle: "High Register Octave Leaps", accuracy: 96.4, centsError: 5.4, stability: 95.2, target: 90, score: 97 },
];

export const mockTempoTrend: IMockTempoTrendPoint[] = [
  { date: "Sep 12", sessionTitle: "Vocal Warmup Arpeggios", measuredBpm: 92, targetBpm: 90, deviation: 2.0, consistency: 91.2 },
  { date: "Sep 14", sessionTitle: "Rolling in the Deep", measuredBpm: 106, targetBpm: 105, deviation: 1.0, consistency: 94.0 },
  { date: "Sep 16", sessionTitle: "Hallelujah", measuredBpm: 61, targetBpm: 60, deviation: 1.0, consistency: 96.5 },
  { date: "Sep 18", sessionTitle: "Passaggio Siren Drills", measuredBpm: 112, targetBpm: 110, deviation: 2.0, consistency: 92.8 },
  { date: "Sep 20", sessionTitle: "O Mio Babbino Caro", measuredBpm: 76, targetBpm: 75, deviation: 1.0, consistency: 95.2 },
  { date: "Sep 22", sessionTitle: "Chandelier - Belt", measuredBpm: 119, targetBpm: 117, deviation: 2.0, consistency: 93.6 },
  { date: "Sep 24", sessionTitle: "Vibrato Centering", measuredBpm: 80, targetBpm: 80, deviation: 0.2, consistency: 98.4 },
  { date: "Sep 26", sessionTitle: "Fly Me to the Moon", measuredBpm: 120, targetBpm: 120, deviation: 0.5, consistency: 97.8 },
  { date: "Sep 28", sessionTitle: "High Register Leaps", measuredBpm: 96, targetBpm: 96, deviation: 0.3, consistency: 98.9 },
];

export const mockVocalRange: IMockVocalRange = {
  lowestNote: "C3",
  lowestFreq: 130.81,
  highestNote: "A5",
  highestFreq: 880.0,
  tessituraStart: "E3",
  tessituraEnd: "C5",
  passaggioNote: "F#4",
  totalSemitones: 34,
  octaveSpan: "2.83 Octaves",
  registers: [
    {
      name: "Chest Voice",
      startNote: "C3",
      endNote: "D4",
      startFreq: 130.81,
      endFreq: 293.66,
      color: "#38bdf8",
      description: "Thick vocal fold vibration with strong fundamental resonance and subglottic pressure.",
    },
    {
      name: "Mixed Voice",
      startNote: "D4",
      endNote: "G4",
      startFreq: 293.66,
      endFreq: 392.0,
      color: "#818cf8",
      description: "Balanced thyroarytenoid & cricothyroid engagement through the lower and upper passaggio.",
    },
    {
      name: "Head Voice",
      startNote: "G4",
      endNote: "E5",
      startFreq: 392.0,
      endFreq: 659.25,
      color: "#c084fc",
      description: "Thin vocal edge vibration with expanded pharyngeal acoustic coupling and high brilliance.",
    },
    {
      name: "Whistle / Bell Register",
      startNote: "E5",
      endNote: "A5",
      startFreq: 659.25,
      endFreq: 880.0,
      color: "#f472b6",
      description: "Posterior vocal fold dampening producing piercing, flute-like acoustic overtones.",
    },
  ],
};

export const mockAiFeedback: IMockAiFeedback = {
  healthScore: 96,
  fatigueRisk: "Low",
  vocalStrainStatus: "Zero Glottal Hyperfunction Detected",
  summary:
    "Formant resonance peaking exceptionally at 2.85 kHz (Singer's Formant). Intonation error across sustained notes reduced by 64% over the last 14 days. Minor flatting tendency observed during ascending fourth leaps into G4.",
  acousticProfile: {
    singersFormantHz: 2850,
    formantClarity: "94.8% Ring Factor",
    vibratoRateHz: 5.82,
    vibratoDepthCents: 52,
    breathEfficiency: 92.4,
  },
  strengths: [
    "Consistent vibrato frequency oscillation maintained within ideal physiological window (5.6 - 6.0 Hz).",
    "Pristine vowel purity on /a/ and /o/ throughout the middle octave (F3 to C5).",
    "Sub-6-cent microtonal centering on sustained tonic and dominant scale degrees.",
  ],
  areasForImprovement: [
    "Slight anticipatory air release on ascending leaps above the first passaggio (E4-F#4).",
    "Soft palate lowering slightly during forte dynamics on /i/ vowels, causing minor nasal resonance.",
  ],
  recommendedDrills: [
    {
      id: "drill-1",
      title: "Octave Siren Glissando on 'Ng'",
      focus: "Passaggio Transition Smoothing",
      duration: "5 mins",
      difficulty: "Intermediate",
      targetArea: "D4 - G4 Mixed Voice",
      instructions: "Perform slow, continuous glissandi from C4 through G4 on a voiced nasal consonant without abrupt timbre shifts.",
    },
    {
      id: "drill-2",
      title: "Staccato Arpeggio on /i/ Vowel",
      focus: "Formant Amplification & Pharyngeal Space",
      duration: "7 mins",
      difficulty: "Advanced",
      targetArea: "A4 - E5 Head Register",
      instructions: "Keep the larynx neutral and soft palate elevated while cleanly pulsing five-tone arpeggios at 112 BPM.",
    },
    {
      id: "drill-3",
      title: "Messa di Voce Dynamic Swell",
      focus: "Subglottic Breath Pressure Balance",
      duration: "6 mins",
      difficulty: "Master",
      targetArea: "C4 - A4 Sustained Tones",
      instructions: "Swell from pianissimo (pp) to fortissimo (ff) and back over 12 seconds while keeping pitch deviation under 4 cents.",
    },
  ],
};

export const mockSessions: ISession[] = [
  {
    _id: "sess-101",
    userId: "user-elena-vance-pro",
    title: "High Register Octave Leaps",
    songTitle: "Vocalise in D Major (Rachmaninoff)",
    audioFileName: "take_2026_09_28_rachmaninoff.wav",
    fileSizeBytes: 8940000,
    durationSeconds: 195,
    overallScore: 97,
    grade: "A+",
    pitchAccuracyScore: 96.4,
    pitchStabilityScore: 95.2,
    centsDeviationAvg: 5.4,
    sharpTendencyPct: 1.8,
    flatTendencyPct: 1.8,
    inTunePercentage: 96.4,
    vibratoRateHz: 5.85,
    vibratoDepthCents: 52,
    vibratoScore: 96,
    dynamicRangeDb: 34.2,
    peakDb: -1.2,
    breathPausesCount: 14,
    lowestNote: "C3",
    highestNote: "A5",
    rangeSemitones: 34,
    voiceTypeDetected: "Lyric Soprano",
    timbreClarityScore: 96.0,
    spectralCentroidHz: 2840,
    resonanceProfile: "Pristine Singer's Formant",
    pitchCurve: [],
    coachingFeedback: {
      summary: "Flawless intonation centering and crystalline high register resonance.",
      strengths: ["Rock-solid vibrato at 5.85 Hz", "Clean leaps to A5", "Zero strain"],
      areas_for_improvement: ["Keep breath steady during final decrescendo"],
      recommended_drills: [],
    },
    tags: ["Classical", "High Tessitura", "Warm-up"],
    createdAt: "2026-09-28T10:15:00.000Z",
    updatedAt: "2026-09-28T10:18:20.000Z",
  },
  {
    _id: "sess-102",
    userId: "user-elena-vance-pro",
    title: "Fly Me to the Moon (Jazz Mix)",
    songTitle: "Fly Me to the Moon",
    audioFileName: "take_2026_09_26_jazz_fly_me.wav",
    fileSizeBytes: 7420000,
    durationSeconds: 165,
    overallScore: 96,
    grade: "A+",
    pitchAccuracyScore: 95.8,
    pitchStabilityScore: 94.5,
    centsDeviationAvg: 6.1,
    sharpTendencyPct: 2.1,
    flatTendencyPct: 2.1,
    inTunePercentage: 95.8,
    vibratoRateHz: 5.75,
    vibratoDepthCents: 48,
    vibratoScore: 95,
    dynamicRangeDb: 28.5,
    peakDb: -2.4,
    breathPausesCount: 12,
    lowestNote: "D3",
    highestNote: "F5",
    rangeSemitones: 27,
    voiceTypeDetected: "Lyric Soprano",
    timbreClarityScore: 95.0,
    spectralCentroidHz: 2720,
    resonanceProfile: "Warm Pharyngeal Resonance",
    pitchCurve: [],
    coachingFeedback: {
      summary: "Exceptional swing tempo consistency and warm, relaxed vocal onset.",
      strengths: ["Natural micro-vibrato", "Effortless phrasing", "Dynamic inflection"],
      areas_for_improvement: ["Articulate trailing sibilants more crisply"],
      recommended_drills: [],
    },
    tags: ["Pop", "Jazz", "Repertoire"],
    createdAt: "2026-09-26T15:20:00.000Z",
    updatedAt: "2026-09-26T15:23:10.000Z",
  },
  {
    _id: "sess-103",
    userId: "user-elena-vance-pro",
    title: "Vibrato Centering Exercise",
    songTitle: "Sustained Tone Calibration",
    audioFileName: "take_2026_09_24_calibration.wav",
    fileSizeBytes: 5200000,
    durationSeconds: 120,
    overallScore: 94,
    grade: "A",
    pitchAccuracyScore: 94.6,
    pitchStabilityScore: 93.8,
    centsDeviationAvg: 7.2,
    sharpTendencyPct: 2.4,
    flatTendencyPct: 3.0,
    inTunePercentage: 94.6,
    vibratoRateHz: 5.8,
    vibratoDepthCents: 50,
    vibratoScore: 94,
    dynamicRangeDb: 22.0,
    peakDb: -3.0,
    breathPausesCount: 8,
    lowestNote: "E3",
    highestNote: "G5",
    rangeSemitones: 28,
    voiceTypeDetected: "Lyric Soprano",
    timbreClarityScore: 93.5,
    spectralCentroidHz: 2650,
    resonanceProfile: "Balanced Acoustic Ring",
    pitchCurve: [],
    coachingFeedback: {
      summary: "Steady breath engagement. Vibrato oscillation is even and controlled.",
      strengths: ["Consistent depth", "No oscillation jitter"],
      areas_for_improvement: ["Smooth out attack on high G5"],
      recommended_drills: [],
    },
    tags: ["Warm-up", "Agility"],
    createdAt: "2026-09-24T18:40:00.000Z",
    updatedAt: "2026-09-24T18:42:15.000Z",
  },
  {
    _id: "sess-104",
    userId: "user-elena-vance-pro",
    title: "Chandelier - Belt & Mix",
    songTitle: "Chandelier (Sia)",
    audioFileName: "take_2026_09_22_chandelier.wav",
    fileSizeBytes: 9800000,
    durationSeconds: 210,
    overallScore: 91,
    grade: "A",
    pitchAccuracyScore: 92.0,
    pitchStabilityScore: 91.0,
    centsDeviationAvg: 9.8,
    sharpTendencyPct: 4.2,
    flatTendencyPct: 3.8,
    inTunePercentage: 92.0,
    vibratoRateHz: 5.9,
    vibratoDepthCents: 56,
    vibratoScore: 90,
    dynamicRangeDb: 38.0,
    peakDb: -0.8,
    breathPausesCount: 18,
    lowestNote: "C3",
    highestNote: "F5",
    rangeSemitones: 29,
    voiceTypeDetected: "Lyric Soprano",
    timbreClarityScore: 92.0,
    spectralCentroidHz: 2980,
    resonanceProfile: "High Energy Belt",
    pitchCurve: [],
    coachingFeedback: {
      summary: "Strong vocal stamina and forward acoustic projection on chorus leaps.",
      strengths: ["Powerful chest-mix transition", "Expressive dynamics"],
      areas_for_improvement: ["Watch out for slight flatting on sustained F5"],
      recommended_drills: [],
    },
    tags: ["Pop", "Belt", "Repertoire"],
    createdAt: "2026-09-22T14:10:00.000Z",
    updatedAt: "2026-09-22T14:14:00.000Z",
  },
  {
    _id: "sess-105",
    userId: "user-elena-vance-pro",
    title: "O Mio Babbino Caro (Tessitura)",
    songTitle: "O Mio Babbino Caro (Puccini)",
    audioFileName: "take_2026_09_20_puccini.wav",
    fileSizeBytes: 8100000,
    durationSeconds: 175,
    overallScore: 93,
    grade: "A",
    pitchAccuracyScore: 93.4,
    pitchStabilityScore: 92.1,
    centsDeviationAvg: 8.6,
    sharpTendencyPct: 3.1,
    flatTendencyPct: 3.5,
    inTunePercentage: 93.4,
    vibratoRateHz: 5.7,
    vibratoDepthCents: 51,
    vibratoScore: 93,
    dynamicRangeDb: 31.0,
    peakDb: -1.8,
    breathPausesCount: 15,
    lowestNote: "E3",
    highestNote: "A5",
    rangeSemitones: 29,
    voiceTypeDetected: "Lyric Soprano",
    timbreClarityScore: 94.0,
    spectralCentroidHz: 2890,
    resonanceProfile: "Open Pharyngeal Dome",
    pitchCurve: [],
    coachingFeedback: {
      summary: "Lyrical legato lines with rich harmonic envelope across the upper octave.",
      strengths: ["Beautiful vowel shading", "Fluid breath support"],
      areas_for_improvement: ["Ease dynamic entry on high Ab5"],
      recommended_drills: [],
    },
    tags: ["Classical", "Tessitura"],
    createdAt: "2026-09-20T11:00:00.000Z",
    updatedAt: "2026-09-20T11:03:30.000Z",
  },
  {
    _id: "sess-106",
    userId: "user-elena-vance-pro",
    title: "Passaggio Siren Drills",
    songTitle: "5-Tone Glissando Series",
    audioFileName: "take_2026_09_18_sirens.wav",
    fileSizeBytes: 4900000,
    durationSeconds: 110,
    overallScore: 89,
    grade: "B+",
    pitchAccuracyScore: 89.8,
    pitchStabilityScore: 88.0,
    centsDeviationAvg: 12.0,
    sharpTendencyPct: 5.1,
    flatTendencyPct: 5.1,
    inTunePercentage: 89.8,
    vibratoRateHz: 5.65,
    vibratoDepthCents: 46,
    vibratoScore: 88,
    dynamicRangeDb: 24.0,
    peakDb: -3.5,
    breathPausesCount: 9,
    lowestNote: "D3",
    highestNote: "G5",
    rangeSemitones: 29,
    voiceTypeDetected: "Lyric Soprano",
    timbreClarityScore: 89.0,
    spectralCentroidHz: 2540,
    resonanceProfile: "Neutral Siren Glissando",
    pitchCurve: [],
    coachingFeedback: {
      summary: "Good pass between chest and head register. Avoid tension in jaw.",
      strengths: ["Even air flow", "Consistent glissando rate"],
      areas_for_improvement: ["Relax tongue root on F#4"],
      recommended_drills: [],
    },
    tags: ["Warm-up", "Agility"],
    createdAt: "2026-09-18T17:30:00.000Z",
    updatedAt: "2026-09-18T17:32:00.000Z",
  },
  {
    _id: "sess-107",
    userId: "user-elena-vance-pro",
    title: "Hallelujah (Vocalise in D)",
    songTitle: "Hallelujah",
    audioFileName: "take_2026_09_16_hallelujah.wav",
    fileSizeBytes: 9100000,
    durationSeconds: 200,
    overallScore: 90,
    grade: "A-",
    pitchAccuracyScore: 91.0,
    pitchStabilityScore: 89.5,
    centsDeviationAvg: 11.2,
    sharpTendencyPct: 4.4,
    flatTendencyPct: 4.6,
    inTunePercentage: 91.0,
    vibratoRateHz: 5.72,
    vibratoDepthCents: 49,
    vibratoScore: 90,
    dynamicRangeDb: 29.0,
    peakDb: -2.0,
    breathPausesCount: 16,
    lowestNote: "C3",
    highestNote: "E5",
    rangeSemitones: 28,
    voiceTypeDetected: "Lyric Soprano",
    timbreClarityScore: 91.0,
    spectralCentroidHz: 2680,
    resonanceProfile: "Warm Cinematic Acoustic",
    pitchCurve: [],
    coachingFeedback: {
      summary: "Emotional connection and sustained resonance throughout mid-register.",
      strengths: ["Intimate dynamic inflection", "Clean onsets"],
      areas_for_improvement: ["Keep pitch centered on descending lines"],
      recommended_drills: [],
    },
    tags: ["Pop", "Repertoire"],
    createdAt: "2026-09-16T19:15:00.000Z",
    updatedAt: "2026-09-16T19:18:40.000Z",
  },
  {
    _id: "sess-108",
    userId: "user-elena-vance-pro",
    title: "Rolling in the Deep (Take 1)",
    songTitle: "Rolling in the Deep (Adele)",
    audioFileName: "take_2026_09_14_adele_take1.wav",
    fileSizeBytes: 8600000,
    durationSeconds: 185,
    overallScore: 88,
    grade: "B+",
    pitchAccuracyScore: 88.5,
    pitchStabilityScore: 87.2,
    centsDeviationAvg: 13.8,
    sharpTendencyPct: 6.2,
    flatTendencyPct: 5.3,
    inTunePercentage: 88.5,
    vibratoRateHz: 5.6,
    vibratoDepthCents: 45,
    vibratoScore: 87,
    dynamicRangeDb: 35.0,
    peakDb: -1.5,
    breathPausesCount: 17,
    lowestNote: "C3",
    highestNote: "D5",
    rangeSemitones: 26,
    voiceTypeDetected: "Lyric Soprano",
    timbreClarityScore: 88.0,
    spectralCentroidHz: 2600,
    resonanceProfile: "Punchy Contemporary Mix",
    pitchCurve: [],
    coachingFeedback: {
      summary: "Strong rhythmic drive. Slight vocal fatigue noted after minute 2.",
      strengths: ["Rhythmic accuracy", "Dynamic bite"],
      areas_for_improvement: ["Avoid pushing chest voice above Eb4"],
      recommended_drills: [],
    },
    tags: ["Pop", "Belt"],
    createdAt: "2026-09-14T16:00:00.000Z",
    updatedAt: "2026-09-14T16:03:20.000Z",
  },
];

export const mockGoals: IGoal[] = [
  {
    _id: "goal-1",
    userId: "user-elena-vance-pro",
    title: "Weekly Practice Time",
    description: "Maintain 5 hours of total deliberate vocal practice per week.",
    category: "PRACTICE_TIME",
    targetValue: 5,
    currentValue: 4.2,
    targetPracticeHours: 5,
    unit: "hrs",
    isCompleted: false,
    createdAt: "2026-09-22T00:00:00.000Z",
  },
  {
    _id: "goal-2",
    userId: "user-elena-vance-pro",
    title: "Pitch Intonation Accuracy",
    description: "Achieve an average pitch accuracy exceeding 92% across all takes.",
    category: "PITCH_ACCURACY",
    targetValue: 92,
    currentValue: 93.8,
    targetPitchAccuracy: 92,
    unit: "%",
    isCompleted: true,
    completedAt: "2026-09-26T12:00:00.000Z",
    createdAt: "2026-09-20T00:00:00.000Z",
  },
  {
    _id: "goal-3",
    userId: "user-elena-vance-pro",
    title: "High Range Extension to A5",
    description: "Comfortably stabilize head register through A5 with zero strain.",
    category: "RANGE_EXPANSION",
    targetValue: 34,
    currentValue: 34,
    unit: "semitones",
    isCompleted: true,
    completedAt: "2026-09-28T10:15:00.000Z",
    createdAt: "2026-09-15T00:00:00.000Z",
  },
  {
    _id: "goal-4",
    userId: "user-elena-vance-pro",
    title: "14-Day Consecutive Practice Streak",
    description: "Sing and record at least 15 minutes every single day.",
    category: "DAILY_STREAK",
    targetValue: 14,
    currentValue: 14,
    unit: "days",
    isCompleted: true,
    completedAt: "2026-09-28T09:00:00.000Z",
    createdAt: "2026-09-14T00:00:00.000Z",
  },
  {
    _id: "goal-5",
    userId: "user-elena-vance-pro",
    title: "Vibrato Stability Index",
    description: "Hold continuous vibrato oscillation between 5.6 Hz and 6.0 Hz.",
    category: "VIBRATO_STABILITY",
    targetValue: 95,
    currentValue: 94.2,
    unit: "%",
    isCompleted: false,
    createdAt: "2026-09-21T00:00:00.000Z",
  },
];

export const mockAchievements: IAchievement[] = [
  {
    _id: "ach-1",
    userId: "user-elena-vance-pro",
    badgeKey: "pitch_maestro",
    title: "Centering Virtuoso",
    description: "Maintained < 6 cents deviation across 5 consecutive practice sessions.",
    icon: "Target",
    category: "INTONATION",
    progress: 5,
    maxProgress: 5,
    isUnlocked: true,
    unlockedAt: "2026-09-28T10:15:00.000Z",
    tier: "Diamond",
  },
  {
    _id: "ach-2",
    userId: "user-elena-vance-pro",
    badgeKey: "streak_titan",
    title: "Two-Week Vocal Ironclad",
    description: "Achieved a 14-day unbroken daily practice streak.",
    icon: "Flame",
    category: "DEDICATION",
    progress: 14,
    maxProgress: 14,
    isUnlocked: true,
    unlockedAt: "2026-09-28T09:00:00.000Z",
    tier: "Gold",
  },
  {
    _id: "ach-3",
    userId: "user-elena-vance-pro",
    badgeKey: "range_pioneer",
    title: "Three-Octave Explorer",
    description: "Expanded total demonstrated vocal range to 34+ semitones.",
    icon: "Music",
    category: "RANGE",
    progress: 34,
    maxProgress: 36,
    isUnlocked: false,
    tier: "Gold",
  },
  {
    _id: "ach-4",
    userId: "user-elena-vance-pro",
    badgeKey: "vibrato_lock",
    title: "Acoustic Resonance Master",
    description: "Recorded a session with Singer's Formant clarity exceeding 95%.",
    icon: "Zap",
    category: "VIBRATO",
    progress: 96,
    maxProgress: 95,
    isUnlocked: true,
    unlockedAt: "2026-09-26T15:20:00.000Z",
    tier: "Silver",
  },
  {
    _id: "ach-5",
    userId: "user-elena-vance-pro",
    badgeKey: "marathon_voice",
    title: "1,000 Minutes of Dedication",
    description: "Logged over 1,000 total minutes of acoustic practice in the studio.",
    icon: "Award",
    category: "MILESTONE",
    progress: 1470,
    maxProgress: 1000,
    isUnlocked: true,
    unlockedAt: "2026-09-18T12:00:00.000Z",
    tier: "Silver",
  },
  {
    _id: "ach-6",
    userId: "user-elena-vance-pro",
    badgeKey: "studio_archivist",
    title: "Century Archivist",
    description: "Log 100 high-fidelity vocal practice takes in your personal cloud.",
    icon: "Library",
    category: "MILESTONE",
    progress: 84,
    maxProgress: 100,
    isUnlocked: false,
    tier: "Bronze",
  },
];

export const mockAnalyticsData = {
  kpis: {
    totalPracticeHours: 24.5,
    totalMinutes: 1470,
    totalSessions: 84,
    streakDays: 14,
    avgPitchAccuracy: 93.8,
    avgTempoStability: 95.4,
    currentRange: "C3 - A5 (34 Semitones)",
    overallScore: 92.4,
    weeklyGrowthPct: 4.6,
    storageUsedBytes: 1488977920, // 1.39 GB
    storageMaxBytes: 5368709120, // 5.0 GB
    weeklyUploadCount: 8,
  },
  pitchTrend: mockPitchTrend,
  tempoTrend: mockTempoTrend,
  vocalRange: mockVocalRange,
  aiFeedback: mockAiFeedback,
  radarMetrics: [
    { subject: "Intonation", score: 94.2, fullMark: 100 },
    { subject: "Stability", score: 91.0, fullMark: 100 },
    { subject: "Vibrato", score: 93.5, fullMark: 100 },
    { subject: "Dynamics", score: 89.0, fullMark: 100 },
    { subject: "Breath Control", score: 92.4, fullMark: 100 },
    { subject: "Timbre Clarity", score: 95.8, fullMark: 100 },
  ],
  weeklyDistribution: [
    { day: "Mon", minutes: 45, sessions: 2 },
    { day: "Tue", minutes: 35, sessions: 1 },
    { day: "Wed", minutes: 50, sessions: 2 },
    { day: "Thu", minutes: 60, sessions: 2 },
    { day: "Fri", minutes: 40, sessions: 1 },
    { day: "Sat", minutes: 80, sessions: 3 },
    { day: "Sun", minutes: 70, sessions: 2 },
  ],
};
